### PR TITLE
Fix #70 - cache dir does not exist

### LINKED ISSUE #70: cache dir does not exist
When running the solve dependencies task the cache dir may not exist and the rake task will fail.  Solution would be to ensure the directory exist.

### PR DESCRIPTION
**Pull request by logicminds**
* Previously if the directory did not exist the rake task would fail
    This will create the necessary directory before using it which
    fixes the problem.

### CODE REVIEW

File: lib/ra10ke/solve.rb [hunk 1]
```diff
@@ -35,6 +36,9 @@ def define_task_solve_dependencies(*_args)
       end
       # Actual new logic begins here:
       cache = (ENV['XDG_CACHE_DIR'] || File.expand_path('~/.cache'))
+
+      FileUtils.mkdir_p(cache) unless Dir.exist?(cache)
```
Comment (kenyon) [inline lib/ra10ke/solve.rb:40]: No need to check for existence with this function.
```suggestion
      FileUtils.mkdir_p(cache)
```

Comment (logicminds) [reply lib/ra10ke/solve.rb]: fixed

**Comment by logicminds** [comment]
@kenyon can you approve.  Since there are no tests, the coverage report is blowing up.   A bigger effort to refactor in order to add tests is required which is not in scope for this change.
